"""initial schema baseline

Revision ID: baec3dbedabf
Revises: 
Create Date: 2026-08-25 19:16:38.136085
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'baec3dbedabf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_action_time', 'audit_log', ['action', 'timestamp'], unique=False)
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_index('ix_audit_user_time', 'audit_log', ['user_id', 'timestamp'], unique=False)
    op.create_table('courts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=False),
    sa.Column('court_type', sa.Enum('CIRCUIT', 'DISTRICT', 'PROBATE', 'COURT_OF_CLAIMS', 'COURT_OF_APPEALS', 'SUPREME_COURT', 'MUNICIPAL', name='courttype'), nullable=False),
    sa.Column('division', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('cms_type', sa.String(length=50), nullable=True),
    sa.Column('is_efiling_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courts_county'), 'courts', ['county'], unique=False)
    op.create_index(op.f('ix_courts_court_type'), 'courts', ['court_type'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', 'WAIVED', name='paymentstatus'), nullable=False),
    sa.Column('payment_method', sa.Enum('CREDIT_CARD', 'DEBIT_CARD', 'ACH', 'WAIVER', name='paymentmethod'), nullable=True),
    sa.Column('transaction_ref', sa.String(length=255), nullable=True),
    sa.Column('payer_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('bar_number', sa.String(length=20), nullable=True),
    sa.Column('bar_number_verified', sa.Boolean(), nullable=False),
    sa.Column('user_type', sa.Enum('ATTORNEY', 'CLERK', 'JUDGE', 'SELF_REPRESENTED', 'PUBLIC', 'ADMIN', name='usertype'), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('firm_name', sa.String(length=255), nullable=True),
    sa.Column('keycloak_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keycloak_id')
    )
    op.create_index(op.f('ix_users_bar_number'), 'users', ['bar_number'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('case_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('court_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('CIVIL', 'CRIMINAL', 'FAMILY', 'PROBATE', 'TRAFFIC', 'SMALL_CLAIMS', 'APPEALS', name='casecategory'), nullable=False),
    sa.Column('filing_fee_cents', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_types_court_id'), 'case_types', ['court_id'], unique=False)
    op.create_table('favorite_courts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('court_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'court_id', name='uq_user_court_favorite')
    )
    op.create_index(op.f('ix_favorite_courts_court_id'), 'favorite_courts', ['court_id'], unique=False)
    op.create_index(op.f('ix_favorite_courts_user_id'), 'favorite_courts', ['user_id'], unique=False)
    op.create_table('user_court_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('court_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('FILER', 'CLERK', 'JUDGE', 'ADMIN', name='courtrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_court_roles_court_id'), 'user_court_roles', ['court_id'], unique=False)
    op.create_index(op.f('ix_user_court_roles_user_id'), 'user_court_roles', ['user_id'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('court_id', sa.Integer(), nullable=False),
    sa.Column('case_number', sa.String(length=50), nullable=False),
    sa.Column('case_type_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('is_sealed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'DISMISSED', 'PENDING', name='casestatus'), nullable=False),
    sa.Column('filed_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('judge_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_type_id'], ['case_types.id'], ),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ),
    sa.ForeignKeyConstraint(['judge_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('court_id', 'case_number', name='uq_case_court_number')
    )
    op.create_index(op.f('ix_cases_case_number'), 'cases', ['case_number'], unique=False)
    op.create_index(op.f('ix_cases_case_type_id'), 'cases', ['case_type_id'], unique=False)
    op.create_index(op.f('ix_cases_court_id'), 'cases', ['court_id'], unique=False)
    op.create_index(op.f('ix_cases_is_sealed'), 'cases', ['is_sealed'], unique=False)
    op.create_index(op.f('ix_cases_judge_id'), 'cases', ['judge_id'], unique=False)
    op.create_table('fee_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('court_id', sa.Integer(), nullable=False),
    sa.Column('case_type_id', sa.Integer(), nullable=True),
    sa.Column('fee_type', sa.String(length=100), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['case_type_id'], ['case_types.id'], ),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_schedules_case_type_id'), 'fee_schedules', ['case_type_id'], unique=False)
    op.create_index(op.f('ix_fee_schedules_court_id'), 'fee_schedules', ['court_id'], unique=False)
    op.create_table('filing_checklists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('court_id', sa.Integer(), nullable=False),
    sa.Column('case_type_id', sa.Integer(), nullable=True),
    sa.Column('motion_type', sa.String(length=100), nullable=False),
    sa.Column('checklist_items', sa.JSON(), nullable=False),
    sa.Column('help_text', sa.Text(), nullable=True),
    sa.Column('mcr_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['case_type_id'], ['case_types.id'], ),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filing_checklists_case_type_id'), 'filing_checklists', ['case_type_id'], unique=False)
    op.create_index(op.f('ix_filing_checklists_court_id'), 'filing_checklists', ['court_id'], unique=False)
    op.create_table('filing_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('court_id', sa.Integer(), nullable=False),
    sa.Column('case_type_id', sa.Integer(), nullable=True),
    sa.Column('document_type_code', sa.String(length=50), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('mcr_reference', sa.String(length=50), nullable=True),
    sa.Column('local_rule_reference', sa.String(length=100), nullable=True),
    sa.Column('page_limit', sa.Integer(), nullable=True),
    sa.Column('format_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['case_type_id'], ['case_types.id'], ),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filing_requirements_case_type_id'), 'filing_requirements', ['case_type_id'], unique=False)
    op.create_index(op.f('ix_filing_requirements_court_id'), 'filing_requirements', ['court_id'], unique=False)
    op.create_table('case_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.Enum('PLAINTIFF', 'DEFENDANT', 'PETITIONER', 'RESPONDENT', 'ATTORNEY_PLAINTIFF', 'ATTORNEY_DEFENDANT', 'GUARDIAN', 'INTERVENOR', name='participantrole'), nullable=False),
    sa.Column('party_name', sa.String(length=255), nullable=False),
    sa.Column('attorney_bar_number', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('contact_address', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_participants_attorney_bar_number'), 'case_participants', ['attorney_bar_number'], unique=False)
    op.create_index(op.f('ix_case_participants_case_id'), 'case_participants', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_participants_party_name'), 'case_participants', ['party_name'], unique=False)
    op.create_index(op.f('ix_case_participants_user_id'), 'case_participants', ['user_id'], unique=False)
    op.create_table('favorite_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'case_id', name='uq_user_case_favorite')
    )
    op.create_index(op.f('ix_favorite_cases_case_id'), 'favorite_cases', ['case_id'], unique=False)
    op.create_index(op.f('ix_favorite_cases_user_id'), 'favorite_cases', ['user_id'], unique=False)
    op.create_table('filing_envelopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('court_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('case_type_id', sa.Integer(), nullable=False),
    sa.Column('filer_id', sa.Integer(), nullable=False),
    sa.Column('filing_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'ACCEPTED', 'REJECTED', 'RETURNED', 'SERVED', name='filingstatus'), nullable=False),
    sa.Column('case_title', sa.String(length=500), nullable=True),
    sa.Column('filing_description', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('fee_waiver_requested', sa.Boolean(), nullable=False),
    sa.Column('fee_waiver_granted', sa.Boolean(), nullable=True),
    sa.Column('fee_waiver_reason', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['case_type_id'], ['case_types.id'], ),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ),
    sa.ForeignKeyConstraint(['filer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_filing_court_status', 'filing_envelopes', ['court_id', 'status'], unique=False)
    op.create_index('ix_filing_court_status_submitted', 'filing_envelopes', ['court_id', 'status', 'submitted_at'], unique=False)
    op.create_index(op.f('ix_filing_envelopes_case_id'), 'filing_envelopes', ['case_id'], unique=False)
    op.create_index(op.f('ix_filing_envelopes_case_type_id'), 'filing_envelopes', ['case_type_id'], unique=False)
    op.create_index(op.f('ix_filing_envelopes_court_id'), 'filing_envelopes', ['court_id'], unique=False)
    op.create_index(op.f('ix_filing_envelopes_filer_id'), 'filing_envelopes', ['filer_id'], unique=False)
    op.create_index(op.f('ix_filing_envelopes_payment_id'), 'filing_envelopes', ['payment_id'], unique=False)
    op.create_index(op.f('ix_filing_envelopes_reviewer_id'), 'filing_envelopes', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_filing_envelopes_status'), 'filing_envelopes', ['status'], unique=False)
    op.create_table('service_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('method', sa.Enum('ELECTRONIC', 'MAIL', 'HAND_DELIVERY', name='servicemethod'), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_contacts_case_id'), 'service_contacts', ['case_id'], unique=False)
    op.create_table('filing_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('envelope_id', sa.Integer(), nullable=False),
    sa.Column('document_type_code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('file_key', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('is_confidential', sa.Boolean(), nullable=False),
    sa.Column('is_text_searchable', sa.Boolean(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['envelope_id'], ['filing_envelopes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filing_documents_envelope_id'), 'filing_documents', ['envelope_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.Enum('FILING_SUBMITTED', 'FILING_ACCEPTED', 'FILING_REJECTED', 'FILING_RETURNED', 'SERVICE_OF_PROCESS', 'CASE_UPDATE', name='notificationtype'), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('filing_envelope_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('delivery_status', sa.Enum('PENDING', 'SENT', 'DELIVERED', 'FAILED', name='deliverystatus'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['filing_envelope_id'], ['filing_envelopes.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_filing_envelope_id'), 'notifications', ['filing_envelope_id'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_filing_envelope_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_filing_documents_envelope_id'), table_name='filing_documents')
    op.drop_table('filing_documents')
    op.drop_index(op.f('ix_service_contacts_case_id'), table_name='service_contacts')
    op.drop_table('service_contacts')
    op.drop_index(op.f('ix_filing_envelopes_status'), table_name='filing_envelopes')
    op.drop_index(op.f('ix_filing_envelopes_reviewer_id'), table_name='filing_envelopes')
    op.drop_index(op.f('ix_filing_envelopes_payment_id'), table_name='filing_envelopes')
    op.drop_index(op.f('ix_filing_envelopes_filer_id'), table_name='filing_envelopes')
    op.drop_index(op.f('ix_filing_envelopes_court_id'), table_name='filing_envelopes')
    op.drop_index(op.f('ix_filing_envelopes_case_type_id'), table_name='filing_envelopes')
    op.drop_index(op.f('ix_filing_envelopes_case_id'), table_name='filing_envelopes')
    op.drop_index('ix_filing_court_status_submitted', table_name='filing_envelopes')
    op.drop_index('ix_filing_court_status', table_name='filing_envelopes')
    op.drop_table('filing_envelopes')
    op.drop_index(op.f('ix_favorite_cases_user_id'), table_name='favorite_cases')
    op.drop_index(op.f('ix_favorite_cases_case_id'), table_name='favorite_cases')
    op.drop_table('favorite_cases')
    op.drop_index(op.f('ix_case_participants_user_id'), table_name='case_participants')
    op.drop_index(op.f('ix_case_participants_party_name'), table_name='case_participants')
    op.drop_index(op.f('ix_case_participants_case_id'), table_name='case_participants')
    op.drop_index(op.f('ix_case_participants_attorney_bar_number'), table_name='case_participants')
    op.drop_table('case_participants')
    op.drop_index(op.f('ix_filing_requirements_court_id'), table_name='filing_requirements')
    op.drop_index(op.f('ix_filing_requirements_case_type_id'), table_name='filing_requirements')
    op.drop_table('filing_requirements')
    op.drop_index(op.f('ix_filing_checklists_court_id'), table_name='filing_checklists')
    op.drop_index(op.f('ix_filing_checklists_case_type_id'), table_name='filing_checklists')
    op.drop_table('filing_checklists')
    op.drop_index(op.f('ix_fee_schedules_court_id'), table_name='fee_schedules')
    op.drop_index(op.f('ix_fee_schedules_case_type_id'), table_name='fee_schedules')
    op.drop_table('fee_schedules')
    op.drop_index(op.f('ix_cases_judge_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_is_sealed'), table_name='cases')
    op.drop_index(op.f('ix_cases_court_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_case_type_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_case_number'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_user_court_roles_user_id'), table_name='user_court_roles')
    op.drop_index(op.f('ix_user_court_roles_court_id'), table_name='user_court_roles')
    op.drop_table('user_court_roles')
    op.drop_index(op.f('ix_favorite_courts_user_id'), table_name='favorite_courts')
    op.drop_index(op.f('ix_favorite_courts_court_id'), table_name='favorite_courts')
    op.drop_table('favorite_courts')
    op.drop_index(op.f('ix_case_types_court_id'), table_name='case_types')
    op.drop_table('case_types')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_bar_number'), table_name='users')
    op.drop_table('users')
    op.drop_table('payments')
    op.drop_index(op.f('ix_courts_court_type'), table_name='courts')
    op.drop_index(op.f('ix_courts_county'), table_name='courts')
    op.drop_table('courts')
    op.drop_index('ix_audit_user_time', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_index('ix_audit_action_time', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
